# Generated by Django 2.2.13 on 2020-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(default='P101', max_length=15)),
                ('ram', models.CharField(max_length=10, null=True)),
                ('hdd', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
